// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqFxe_vzrir0D2C9t0-4DdLpw9VsZB5ps',
    appId: '1:534633507068:web:170c904370519540f94f79',
    messagingSenderId: '534633507068',
    projectId: 'careclub-dd963',
    authDomain: 'careclub-dd963.firebaseapp.com',
    storageBucket: 'careclub-dd963.appspot.com',
    measurementId: 'G-1EJZWWQ9GV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQmZ7LgQVZsXt6sDBmofADA3P1Sca9mIk',
    appId: '1:534633507068:android:e48f036ff4d5bd31f94f79',
    messagingSenderId: '534633507068',
    projectId: 'careclub-dd963',
    storageBucket: 'careclub-dd963.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAsbpS4V-Q-HaxQV3aoxk0ONW4fGNKl2Mw',
    appId: '1:534633507068:ios:56c19c21d5b889a2f94f79',
    messagingSenderId: '534633507068',
    projectId: 'careclub-dd963',
    storageBucket: 'careclub-dd963.appspot.com',
    iosClientId: '534633507068-g9qlo6esoccedfrjlnaj9n1aieobcpqd.apps.googleusercontent.com',
    iosBundleId: 'com.careclub.careClub',
  );
}
